name: Swift Build

on: 
  pull_request:
     branches:
     - master

jobs:
  build:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: Switch to Xcode 11
      run: sudo xcode-select -switch /Applications/Xcode_11.app
    - name: Build Swift Package
      run:  swift build
